#!/usr/bin/python

# 
# generate dhcp scopes from google spreadsheet
# nat@nuqe.net
#

import gdata.spreadsheet.service
import gdata.spreadsheet.text_db
import ipcalc
import time

spreadsheet_key = "0AriFdfLzFu4-dHlsX21Fd2tNSldIVGhabTc1WnZpeEE"
worksheet_id = "od0"
configfile4 = "/etc/dhcp/dhcpd-subnets.conf"
configfile6 = "/etc/dhcp/dhcpd6-subnets.conf"

spr_client = gdata.spreadsheet.service.SpreadsheetsService()
spr_client.email = ""
spr_client.password = ""
spr_client.source = "emfcamp dhcp geneartor"
spr_client.ProgrammaticLogin()

q = gdata.spreadsheet.service.ListQuery()
q.orderby = 'column:subnet'
feed = spr_client.GetListFeed(spreadsheet_key, worksheet_id, query=q)

f4 = open(configfile4, "w")
f6 = open(configfile6, "w")

f4.write("#\n")
f4.write("# generated by /root/gen-dhcp.py from EMFCAMP2012 Google Spreadsheet\n")
f4.write("# %s %s\n" % (time.strftime('%m/%d/%Y'),time.strftime('%H:%M:%S')))
f4.write("#\n")

f6.write("#\n")
f6.write("# generated by /root/gen-dhcp.py from EMFCAMP2012 Google Spreadsheet\n")
f6.write("# %s %s\n" % (time.strftime('%m/%d/%Y'),time.strftime('%H:%M:%S')))
f6.write("#\n")

scopes4 = 0
scopes6 = 0
for row_entry in feed.entry:
  record = gdata.spreadsheet.text_db.Record(row_entry=row_entry)
  version = record.content['version']
  if version == "4":
    scopes4 = scopes4 + 1
    subnet = ipcalc.Network(record.content['subnet'])
    f4.write("\n")
    f4.write("# %s: %s\n" % (record.content['type'],record.content['name']))
    f4.write("shared-network %s%s {\n" % (record.content['type'],record.content['name']))
    f4.write("  subnet %s netmask %s {\n" % (subnet.network(), subnet.netmask()))
    f4.write("    range %s %s;\n" % (record.content['start'],record.content['finish']))
    f4.write("    option domain-name-servers %s,%s;\n" % (record.content['resolver1'],record.content['resolver2']))
    f4.write("    option routers %s;\n" % (subnet.host_first()))
    f4.write("  }\n")
    f4.write("}\n")

  if version == "6":
    scopes6 = scopes6 + 1
    subnet = record.content['subnet']
    f6.write("\n")
    f6.write("# %s: %s\n" % (record.content['type'],record.content['name']))
    f6.write("shared-network %s%s {\n" % (record.content['type'],record.content['name']))
    f6.write("  subnet6 %s {\n" % (subnet))
    f6.write("    range6 %s %s;\n" % (record.content['start'],record.content['finish']))
    f6.write("    option dhcp6.name-servers %s,%s;\n" % (record.content['resolver1'],record.content['resolver2']))
    f6.write("  }\n")
    f6.write("}\n")

f4.close()

print "Updated %s with %s scopes" % (configfile4,scopes4)
print "Updated %s with %s scopes" % (configfile6,scopes6)
